### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by mht-sharma**
Add documentation

### CODE REVIEW

**Comment by regisss** [comment]
@mht-sharma @mfuntowicz I'll wait for you to merge this PR (I don't know Mohit if the doc is ready on your side) to test if the PR doc is properly generated, uploaded and retrieved. And then I'll open a PR in Optimum to add it to the main doc.

**Comment by mht-sharma** [comment]
> @mht-sharma @mfuntowicz I'll wait for you to merge this PR (I don't know Mohit if the doc is ready on your side) to test if the PR doc is properly generated, uploaded and retrieved. And then I'll open a PR in Optimum to add it to the main doc.

Thanks @regisss, I have done changes from my side.

**Comment by mfuntowicz** [comment]
@mht-sharma can you start drafting a release notes to publish along with the release? 🙂

Let's do a proper release early next week this way

**Comment by mfuntowicz** [comment]
@regisss @mht-sharma I'm not familiar with the documentation builder, @regisss do you want to review the high-level? 

Otherwise i think we can merge this one, check the doc builder output and address in a second PR.

Approving for now to help moving forward.

**Review by mfuntowicz — APPROVED** [review]

**Comment by regisss** [comment]
@mfuntowicz It looks good on my side, I pushed a couple of commits to add what was missing. Let's merge it!

Then, I'll check if the PR doc works correctly (and fix it if necessary) and open a PR in Optimum to add the doc for Optimum Furiosa.

**Pull request merged**
